/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_slam2_orb_orb_slam2_android_as_OrbNdkHelper */

#ifndef _Included_android_slam2_orb_orb_slam2_android_as_OrbNdkHelper
#define _Included_android_slam2_orb_orb_slam2_android_as_OrbNdkHelper
#ifdef __cplusplus
extern "C" {
#endif

JavaVM* jvm;

/*
 * Class:     android_slam2_orb_orb_slam2_android_as_OrbNdkHelper
 * Method:    initSystemWithParameters
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_slam2_orb_orb_1slam2_1android_1as_OrbNdkHelper_initSystemWithParameters
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     android_slam2_orb_orb_slam2_android_as_OrbNdkHelper
 * Method:    startCurrentORB
 * Signature: (D[III)[I
 */
JNIEXPORT jintArray JNICALL Java_android_slam2_orb_orb_1slam2_1android_1as_OrbNdkHelper_startCurrentORB
  (JNIEnv *, jclass, jdouble, jintArray, jint, jint);

/*
 * Class:     android_slam2_orb_orb_slam2_android_as_OrbNdkHelper
 * Method:    startCurrentORBForCamera
 * Signature: (DJII)[I
 */
JNIEXPORT jintArray JNICALL Java_android_slam2_orb_orb_1slam2_1android_1as_OrbNdkHelper_startCurrentORBForCamera
  (JNIEnv *, jclass, jdouble, jlong, jint, jint);

/*
 * Class:     android_slam2_orb_orb_slam2_android_as_OrbNdkHelper
 * Method:    glesInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_slam2_orb_orb_1slam2_1android_1as_OrbNdkHelper_glesInit
  (JNIEnv *, jclass);

/*
 * Class:     android_slam2_orb_orb_slam2_android_as_OrbNdkHelper
 * Method:    glesRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_slam2_orb_orb_1slam2_1android_1as_OrbNdkHelper_glesRender
  (JNIEnv *, jclass);

/*
 * Class:     android_slam2_orb_orb_slam2_android_as_OrbNdkHelper
 * Method:    glesResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_slam2_orb_orb_1slam2_1android_1as_OrbNdkHelper_glesResize
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
